language: java
jdk:
 - openjdk8
before_install:
 - chmod +x mvnw
before_deploy:
 - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  skip_cleanup: true
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "brunos-crm-api-test"