auth0:
  audience: ${auth0Audience}
  domain: ${auth0Domain}
  connection: ${auth0Connection}
  token: ${auth0ManagementToken}
  client-id: ${auth0ClientId}
  client-secret: ${auth0ClientSecret}
spring:
  data:
    rest:
      base-path: /api/v1
  datasource:
    url: jdbc:h2:mem:nutritionix
    username: sa
    password:
    platform: h2
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt.issuer-uri: https://${auth0.domain}/
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
foodLog:
  secretKey: custom