spring:
  data:
    rest:
      base-path: /api/v1
  datasource:
    url: jdbc:h2:mem:nutritionix
    username: sa
    password:
    platform: h2
    hikari:
      connection-test-query: SELECT 1
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
nutritionix:
  apiKey: 6407fc80a18451eda112d45cd5690a60
  appId: b2051e51
foodLog:
  secretKey: custom